[project]
name = "projet-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django==5.2.*",
    "python-dotenv>=1.2.3",
]

[project.scripts]
projet-uv = "projet_uv:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
