# Generated by Django 5.2.17 on 2026-10-05 15:47

import EntreprisesApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntreprisesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='adresse',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20, 'Ladresse doit contenir au moins 20 caracteres')]),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='matricule_fiscal',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Format non conforme', regex='^\\d{7}[/ -]?[A-Za-z][/ -]?[ABDNPEabdnpe][/ -]?[MPCNEmpcne][/ -]\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[EntreprisesApp.models.validate_email]),
        ),
    ]
