# Generated by Django 5.2.17 on 2026-10-07 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntreprisesApp', '0002_alter_entreprise_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='user_id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Le id doit respecter le format.', regex='^AUser\\d{2}$')]),
        ),
    ]
