# Generated by Django 5.2.17 on 2026-10-07 20:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffresApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='delai_jours',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='offre',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
