# Generated by Django 5.2.17 on 2026-10-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VehiculesApp', '0002_alter_vehicule_capacite_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='updated_at',
        ),
    ]
